services:
  ft-server:
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: fitnessTracker
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      PUBLIC_URL: http://localhost:8080
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    volumes:
      - .:/var/www/html
    depends_on:
      - ft-db

  ft-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: fitnessTracker
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
